blog_redirection:
    path: /
    defaults: { _controller: BlogBundle:Advert:redi }

blog_homepage:
    path:     /accueil
    defaults: { _controller: BlogBundle:Advert:index }

blog_ajout:
    path:     /accueil/ajout
    defaults: { _controller: BlogBundle:Mainpage:printAreaText }

blog_ListeTorrent:
    path:     /accueil/liste
    defaults: { _controller: BlogBundle:Mainpage:liste }

blog_gestion:
    path:     /accueil/gestion
    defaults: { _controller: BlogBundle:Mainpage:gestion }

blog_gestionAjout:
    path:     /accueil/ajout2
    defaults: { _controller: BlogBundle:Mainpage:ajout }


 
