blog_redirection:
    path: /
    defaults: { _controller: BlogBundle:Advert:redi }

blog_homepage:
    path:     /accueil
    defaults: { _controller: BlogBundle:Advert:index }

blog_ajout:
    path:     /accueil/ajout
    defaults: { _controller: BlogBundle:Mainpage:ajout }

blog_ListeTorrent:
    path:     /accueil/ajout/liste
    defaults: { _controller: BlogBundle:Mainpage:liste }


blog_gestion:
    path:     /accueil/ajout/liste/gestion
    defaults: { _controller: BlogBundle:Mainpage:gestion }


 
