blog_redirection:
    path: /
    defaults: { _controller: BlogBundle:Advert:redi }

blog_homepage:
    path:     /accueil
    defaults: { _controller: BlogBundle:Advert:index }

blog_ListeTorrent:
    path:     /accueil/torrent
    defaults: { _controller: BlogBundle:Mainpage:index }

blog_ajout:
    path:     /accueil/torrent/ajout
    defaults: { _controller: BlogBundle:Mainpage:ajout }


 
